---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  finalizers: []
  labels:
    app: "activemq-artemis"
  name: "activemq-artemis-service"
  namespace: "default"
  ownerReferences: []
spec:
  externalIPs: []
  loadBalancerSourceRanges: []
  ports:
  - port: 61616
    name: jms              
  selector:
    app: "activemq-artemis"
  type: "NodePort"
